/**
 * Generated by scripts/generate-exercise-frames.mjs — do not edit by hand.
 *
 * Maps each catalog exercise slug to its first pose frame (frame-1.png).
 * Literal require() paths are required by React Native/Metro.
 * Artwork: Everkinetic, expanded by Bryl Lim (CC BY-SA 4.0).
 */
import type { ImageSourcePropType } from 'react-native';

const frame_bench_press = require('@bryllim/workout-guide/assets/bench-press/frame-1.png') as ImageSourcePropType;
const frame_incline_bench_press = require('@bryllim/workout-guide/assets/incline-bench-press/frame-1.png') as ImageSourcePropType;
const frame_incline_dumbbell_press = require('@bryllim/workout-guide/assets/incline-dumbbell-press/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_bench_press = require('@bryllim/workout-guide/assets/dumbbell-bench-press/frame-1.png') as ImageSourcePropType;
const frame_decline_bench_press = require('@bryllim/workout-guide/assets/decline-bench-press/frame-1.png') as ImageSourcePropType;
const frame_machine_chest_press = require('@bryllim/workout-guide/assets/machine-chest-press/frame-1.png') as ImageSourcePropType;
const frame_pec_deck = require('@bryllim/workout-guide/assets/pec-deck/frame-1.png') as ImageSourcePropType;
const frame_cable_fly = require('@bryllim/workout-guide/assets/cable-fly/frame-1.png') as ImageSourcePropType;
const frame_push_up = require('@bryllim/workout-guide/assets/push-up/frame-1.png') as ImageSourcePropType;
const frame_weighted_push_up = require('@bryllim/workout-guide/assets/weighted-push-up/frame-1.png') as ImageSourcePropType;
const frame_overhead_press = require('@bryllim/workout-guide/assets/overhead-press/frame-1.png') as ImageSourcePropType;
const frame_seated_dumbbell_press = require('@bryllim/workout-guide/assets/seated-dumbbell-press/frame-1.png') as ImageSourcePropType;
const frame_arnold_press = require('@bryllim/workout-guide/assets/arnold-press/frame-1.png') as ImageSourcePropType;
const frame_lateral_raise = require('@bryllim/workout-guide/assets/lateral-raise/frame-1.png') as ImageSourcePropType;
const frame_cable_lateral_raise = require('@bryllim/workout-guide/assets/cable-lateral-raise/frame-1.png') as ImageSourcePropType;
const frame_front_raise = require('@bryllim/workout-guide/assets/front-raise/frame-1.png') as ImageSourcePropType;
const frame_rear_delt_fly = require('@bryllim/workout-guide/assets/rear-delt-fly/frame-1.png') as ImageSourcePropType;
const frame_reverse_pec_deck = require('@bryllim/workout-guide/assets/reverse-pec-deck/frame-1.png') as ImageSourcePropType;
const frame_face_pull = require('@bryllim/workout-guide/assets/face-pull/frame-1.png') as ImageSourcePropType;
const frame_upright_row = require('@bryllim/workout-guide/assets/upright-row/frame-1.png') as ImageSourcePropType;
const frame_deadlift = require('@bryllim/workout-guide/assets/deadlift/frame-1.png') as ImageSourcePropType;
const frame_romanian_deadlift = require('@bryllim/workout-guide/assets/romanian-deadlift/frame-1.png') as ImageSourcePropType;
const frame_barbell_row = require('@bryllim/workout-guide/assets/barbell-row/frame-1.png') as ImageSourcePropType;
const frame_t_bar_row = require('@bryllim/workout-guide/assets/t-bar-row/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_bent_over_row = require('@bryllim/workout-guide/assets/dumbbell-bent-over-row/frame-1.png') as ImageSourcePropType;
const frame_one_arm_dumbbell_row = require('@bryllim/workout-guide/assets/one-arm-dumbbell-row/frame-1.png') as ImageSourcePropType;
const frame_chest_supported_row = require('@bryllim/workout-guide/assets/chest-supported-row/frame-1.png') as ImageSourcePropType;
const frame_seated_row = require('@bryllim/workout-guide/assets/seated-row/frame-1.png') as ImageSourcePropType;
const frame_machine_row = require('@bryllim/workout-guide/assets/machine-row/frame-1.png') as ImageSourcePropType;
const frame_lat_pulldown = require('@bryllim/workout-guide/assets/lat-pulldown/frame-1.png') as ImageSourcePropType;
const frame_close_grip_lat_pulldown = require('@bryllim/workout-guide/assets/close-grip-lat-pulldown/frame-1.png') as ImageSourcePropType;
const frame_straight_arm_pulldown = require('@bryllim/workout-guide/assets/straight-arm-pulldown/frame-1.png') as ImageSourcePropType;
const frame_pull_up = require('@bryllim/workout-guide/assets/pull-up/frame-1.png') as ImageSourcePropType;
const frame_assisted_pull_up = require('@bryllim/workout-guide/assets/assisted-pull-up/frame-1.png') as ImageSourcePropType;
const frame_weighted_pull_up = require('@bryllim/workout-guide/assets/weighted-pull-up/frame-1.png') as ImageSourcePropType;
const frame_chin_up = require('@bryllim/workout-guide/assets/chin-up/frame-1.png') as ImageSourcePropType;
const frame_shrug = require('@bryllim/workout-guide/assets/shrug/frame-1.png') as ImageSourcePropType;
const frame_squat = require('@bryllim/workout-guide/assets/squat/frame-1.png') as ImageSourcePropType;
const frame_front_squat = require('@bryllim/workout-guide/assets/front-squat/frame-1.png') as ImageSourcePropType;
const frame_hack_squat = require('@bryllim/workout-guide/assets/hack-squat/frame-1.png') as ImageSourcePropType;
const frame_leg_press = require('@bryllim/workout-guide/assets/leg-press/frame-1.png') as ImageSourcePropType;
const frame_bulgarian_split_squat = require('@bryllim/workout-guide/assets/bulgarian-split-squat/frame-1.png') as ImageSourcePropType;
const frame_walking_lunge = require('@bryllim/workout-guide/assets/walking-lunge/frame-1.png') as ImageSourcePropType;
const frame_step_up = require('@bryllim/workout-guide/assets/step-up/frame-1.png') as ImageSourcePropType;
const frame_leg_extension = require('@bryllim/workout-guide/assets/leg-extension/frame-1.png') as ImageSourcePropType;
const frame_leg_curl = require('@bryllim/workout-guide/assets/leg-curl/frame-1.png') as ImageSourcePropType;
const frame_seated_leg_curl = require('@bryllim/workout-guide/assets/seated-leg-curl/frame-1.png') as ImageSourcePropType;
const frame_hip_thrust = require('@bryllim/workout-guide/assets/hip-thrust/frame-1.png') as ImageSourcePropType;
const frame_glute_bridge = require('@bryllim/workout-guide/assets/glute-bridge/frame-1.png') as ImageSourcePropType;
const frame_good_morning = require('@bryllim/workout-guide/assets/good-morning/frame-1.png') as ImageSourcePropType;
const frame_standing_calf_raise = require('@bryllim/workout-guide/assets/standing-calf-raise/frame-1.png') as ImageSourcePropType;
const frame_seated_calf_raise = require('@bryllim/workout-guide/assets/seated-calf-raise/frame-1.png') as ImageSourcePropType;
const frame_bicep_curl = require('@bryllim/workout-guide/assets/bicep-curl/frame-1.png') as ImageSourcePropType;
const frame_hammer_curl = require('@bryllim/workout-guide/assets/hammer-curl/frame-1.png') as ImageSourcePropType;
const frame_preacher_curl = require('@bryllim/workout-guide/assets/preacher-curl/frame-1.png') as ImageSourcePropType;
const frame_cable_curl = require('@bryllim/workout-guide/assets/cable-curl/frame-1.png') as ImageSourcePropType;
const frame_reverse_curl = require('@bryllim/workout-guide/assets/reverse-curl/frame-1.png') as ImageSourcePropType;
const frame_wrist_curl = require('@bryllim/workout-guide/assets/wrist-curl/frame-1.png') as ImageSourcePropType;
const frame_tricep_pushdown = require('@bryllim/workout-guide/assets/tricep-pushdown/frame-1.png') as ImageSourcePropType;
const frame_overhead_tricep_extension = require('@bryllim/workout-guide/assets/overhead-tricep-extension/frame-1.png') as ImageSourcePropType;
const frame_skull_crusher = require('@bryllim/workout-guide/assets/skull-crusher/frame-1.png') as ImageSourcePropType;
const frame_close_grip_bench_press = require('@bryllim/workout-guide/assets/close-grip-bench-press/frame-1.png') as ImageSourcePropType;
const frame_dip = require('@bryllim/workout-guide/assets/dip/frame-1.png') as ImageSourcePropType;
const frame_assisted_dip = require('@bryllim/workout-guide/assets/assisted-dip/frame-1.png') as ImageSourcePropType;
const frame_plank = require('@bryllim/workout-guide/assets/plank/frame-1.png') as ImageSourcePropType;
const frame_side_plank = require('@bryllim/workout-guide/assets/side-plank/frame-1.png') as ImageSourcePropType;
const frame_hanging_leg_raise = require('@bryllim/workout-guide/assets/hanging-leg-raise/frame-1.png') as ImageSourcePropType;
const frame_cable_crunch = require('@bryllim/workout-guide/assets/cable-crunch/frame-1.png') as ImageSourcePropType;
const frame_ab_wheel = require('@bryllim/workout-guide/assets/ab-wheel/frame-1.png') as ImageSourcePropType;
const frame_running = require('@bryllim/workout-guide/assets/running/frame-1.png') as ImageSourcePropType;
const frame_walking = require('@bryllim/workout-guide/assets/walking/frame-1.png') as ImageSourcePropType;
const frame_cycling = require('@bryllim/workout-guide/assets/cycling/frame-1.png') as ImageSourcePropType;
const frame_rowing = require('@bryllim/workout-guide/assets/rowing/frame-1.png') as ImageSourcePropType;
const frame_stair_climber = require('@bryllim/workout-guide/assets/stair-climber/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_fly = require('@bryllim/workout-guide/assets/dumbbell-fly/frame-1.png') as ImageSourcePropType;
const frame_incline_cable_fly = require('@bryllim/workout-guide/assets/incline-cable-fly/frame-1.png') as ImageSourcePropType;
const frame_decline_dumbbell_press = require('@bryllim/workout-guide/assets/decline-dumbbell-press/frame-1.png') as ImageSourcePropType;
const frame_smith_machine_bench_press = require('@bryllim/workout-guide/assets/smith-machine-bench-press/frame-1.png') as ImageSourcePropType;
const frame_landmine_press = require('@bryllim/workout-guide/assets/landmine-press/frame-1.png') as ImageSourcePropType;
const frame_chest_dip = require('@bryllim/workout-guide/assets/chest-dip/frame-1.png') as ImageSourcePropType;
const frame_weighted_dip = require('@bryllim/workout-guide/assets/weighted-dip/frame-1.png') as ImageSourcePropType;
const frame_machine_shoulder_press = require('@bryllim/workout-guide/assets/machine-shoulder-press/frame-1.png') as ImageSourcePropType;
const frame_standing_dumbbell_press = require('@bryllim/workout-guide/assets/standing-dumbbell-press/frame-1.png') as ImageSourcePropType;
const frame_push_press = require('@bryllim/workout-guide/assets/push-press/frame-1.png') as ImageSourcePropType;
const frame_machine_lateral_raise = require('@bryllim/workout-guide/assets/machine-lateral-raise/frame-1.png') as ImageSourcePropType;
const frame_cable_front_raise = require('@bryllim/workout-guide/assets/cable-front-raise/frame-1.png') as ImageSourcePropType;
const frame_plate_front_raise = require('@bryllim/workout-guide/assets/plate-front-raise/frame-1.png') as ImageSourcePropType;
const frame_bent_over_rear_delt_raise = require('@bryllim/workout-guide/assets/bent-over-rear-delt-raise/frame-1.png') as ImageSourcePropType;
const frame_cable_rear_delt_fly = require('@bryllim/workout-guide/assets/cable-rear-delt-fly/frame-1.png') as ImageSourcePropType;
const frame_pendlay_row = require('@bryllim/workout-guide/assets/pendlay-row/frame-1.png') as ImageSourcePropType;
const frame_inverted_row = require('@bryllim/workout-guide/assets/inverted-row/frame-1.png') as ImageSourcePropType;
const frame_meadows_row = require('@bryllim/workout-guide/assets/meadows-row/frame-1.png') as ImageSourcePropType;
const frame_single_arm_cable_row = require('@bryllim/workout-guide/assets/single-arm-cable-row/frame-1.png') as ImageSourcePropType;
const frame_wide_grip_lat_pulldown = require('@bryllim/workout-guide/assets/wide-grip-lat-pulldown/frame-1.png') as ImageSourcePropType;
const frame_neutral_grip_pull_up = require('@bryllim/workout-guide/assets/neutral-grip-pull-up/frame-1.png') as ImageSourcePropType;
const frame_assisted_chin_up = require('@bryllim/workout-guide/assets/assisted-chin-up/frame-1.png') as ImageSourcePropType;
const frame_weighted_chin_up = require('@bryllim/workout-guide/assets/weighted-chin-up/frame-1.png') as ImageSourcePropType;
const frame_rack_pull = require('@bryllim/workout-guide/assets/rack-pull/frame-1.png') as ImageSourcePropType;
const frame_back_extension = require('@bryllim/workout-guide/assets/back-extension/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_shrug = require('@bryllim/workout-guide/assets/dumbbell-shrug/frame-1.png') as ImageSourcePropType;
const frame_goblet_squat = require('@bryllim/workout-guide/assets/goblet-squat/frame-1.png') as ImageSourcePropType;
const frame_smith_machine_squat = require('@bryllim/workout-guide/assets/smith-machine-squat/frame-1.png') as ImageSourcePropType;
const frame_belt_squat = require('@bryllim/workout-guide/assets/belt-squat/frame-1.png') as ImageSourcePropType;
const frame_sumo_deadlift = require('@bryllim/workout-guide/assets/sumo-deadlift/frame-1.png') as ImageSourcePropType;
const frame_trap_bar_deadlift = require('@bryllim/workout-guide/assets/trap-bar-deadlift/frame-1.png') as ImageSourcePropType;
const frame_lying_leg_curl = require('@bryllim/workout-guide/assets/lying-leg-curl/frame-1.png') as ImageSourcePropType;
const frame_nordic_hamstring_curl = require('@bryllim/workout-guide/assets/nordic-hamstring-curl/frame-1.png') as ImageSourcePropType;
const frame_single_leg_romanian_deadlift = require('@bryllim/workout-guide/assets/single-leg-romanian-deadlift/frame-1.png') as ImageSourcePropType;
const frame_reverse_lunge = require('@bryllim/workout-guide/assets/reverse-lunge/frame-1.png') as ImageSourcePropType;
const frame_split_squat = require('@bryllim/workout-guide/assets/split-squat/frame-1.png') as ImageSourcePropType;
const frame_cable_kickback = require('@bryllim/workout-guide/assets/cable-kickback/frame-1.png') as ImageSourcePropType;
const frame_hip_abduction_machine = require('@bryllim/workout-guide/assets/hip-abduction-machine/frame-1.png') as ImageSourcePropType;
const frame_single_leg_glute_bridge = require('@bryllim/workout-guide/assets/single-leg-glute-bridge/frame-1.png') as ImageSourcePropType;
const frame_barbell_glute_bridge = require('@bryllim/workout-guide/assets/barbell-glute-bridge/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_glute_bridge = require('@bryllim/workout-guide/assets/dumbbell-glute-bridge/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_hip_thrust = require('@bryllim/workout-guide/assets/dumbbell-hip-thrust/frame-1.png') as ImageSourcePropType;
const frame_smith_machine_hip_thrust = require('@bryllim/workout-guide/assets/smith-machine-hip-thrust/frame-1.png') as ImageSourcePropType;
const frame_smith_machine_romanian_deadlift = require('@bryllim/workout-guide/assets/smith-machine-romanian-deadlift/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_romanian_deadlift = require('@bryllim/workout-guide/assets/dumbbell-romanian-deadlift/frame-1.png') as ImageSourcePropType;
const frame_kettlebell_romanian_deadlift = require('@bryllim/workout-guide/assets/kettlebell-romanian-deadlift/frame-1.png') as ImageSourcePropType;
const frame_cable_pull_through = require('@bryllim/workout-guide/assets/cable-pull-through/frame-1.png') as ImageSourcePropType;
const frame_machine_glute_kickback = require('@bryllim/workout-guide/assets/machine-glute-kickback/frame-1.png') as ImageSourcePropType;
const frame_cable_standing_hip_abduction = require('@bryllim/workout-guide/assets/cable-standing-hip-abduction/frame-1.png') as ImageSourcePropType;
const frame_cable_standing_hip_adduction = require('@bryllim/workout-guide/assets/cable-standing-hip-adduction/frame-1.png') as ImageSourcePropType;
const frame_hip_adduction_machine = require('@bryllim/workout-guide/assets/hip-adduction-machine/frame-1.png') as ImageSourcePropType;
const frame_smith_machine_bulgarian_split_squat = require('@bryllim/workout-guide/assets/smith-machine-bulgarian-split-squat/frame-1.png') as ImageSourcePropType;
const frame_smith_machine_reverse_lunge = require('@bryllim/workout-guide/assets/smith-machine-reverse-lunge/frame-1.png') as ImageSourcePropType;
const frame_smith_machine_split_squat = require('@bryllim/workout-guide/assets/smith-machine-split-squat/frame-1.png') as ImageSourcePropType;
const frame_heel_elevated_goblet_squat = require('@bryllim/workout-guide/assets/heel-elevated-goblet-squat/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_sumo_squat = require('@bryllim/workout-guide/assets/dumbbell-sumo-squat/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_sumo_deadlift = require('@bryllim/workout-guide/assets/dumbbell-sumo-deadlift/frame-1.png') as ImageSourcePropType;
const frame_front_foot_elevated_split_squat = require('@bryllim/workout-guide/assets/front-foot-elevated-split-squat/frame-1.png') as ImageSourcePropType;
const frame_deficit_reverse_lunge = require('@bryllim/workout-guide/assets/deficit-reverse-lunge/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_lateral_lunge = require('@bryllim/workout-guide/assets/dumbbell-lateral-lunge/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_curtsy_lunge = require('@bryllim/workout-guide/assets/dumbbell-curtsy-lunge/frame-1.png') as ImageSourcePropType;
const frame_landmine_squat = require('@bryllim/workout-guide/assets/landmine-squat/frame-1.png') as ImageSourcePropType;
const frame_landmine_romanian_deadlift = require('@bryllim/workout-guide/assets/landmine-romanian-deadlift/frame-1.png') as ImageSourcePropType;
const frame_kettlebell_swing = require('@bryllim/workout-guide/assets/kettlebell-swing/frame-1.png') as ImageSourcePropType;
const frame_glute_focused_back_extension = require('@bryllim/workout-guide/assets/glute-focused-back-extension/frame-1.png') as ImageSourcePropType;
const frame_reverse_hyperextension = require('@bryllim/workout-guide/assets/reverse-hyperextension/frame-1.png') as ImageSourcePropType;
const frame_donkey_calf_raise = require('@bryllim/workout-guide/assets/donkey-calf-raise/frame-1.png') as ImageSourcePropType;
const frame_leg_press_calf_raise = require('@bryllim/workout-guide/assets/leg-press-calf-raise/frame-1.png') as ImageSourcePropType;
const frame_wall_sit = require('@bryllim/workout-guide/assets/wall-sit/frame-1.png') as ImageSourcePropType;
const frame_jump_squat = require('@bryllim/workout-guide/assets/jump-squat/frame-1.png') as ImageSourcePropType;
const frame_incline_dumbbell_curl = require('@bryllim/workout-guide/assets/incline-dumbbell-curl/frame-1.png') as ImageSourcePropType;
const frame_concentration_curl = require('@bryllim/workout-guide/assets/concentration-curl/frame-1.png') as ImageSourcePropType;
const frame_ez_bar_curl = require('@bryllim/workout-guide/assets/ez-bar-curl/frame-1.png') as ImageSourcePropType;
const frame_spider_curl = require('@bryllim/workout-guide/assets/spider-curl/frame-1.png') as ImageSourcePropType;
const frame_rope_hammer_curl = require('@bryllim/workout-guide/assets/rope-hammer-curl/frame-1.png') as ImageSourcePropType;
const frame_drag_curl = require('@bryllim/workout-guide/assets/drag-curl/frame-1.png') as ImageSourcePropType;
const frame_rope_tricep_pushdown = require('@bryllim/workout-guide/assets/rope-tricep-pushdown/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_skull_crusher = require('@bryllim/workout-guide/assets/dumbbell-skull-crusher/frame-1.png') as ImageSourcePropType;
const frame_single_dumbbell_skullcrusher = require('@bryllim/workout-guide/assets/single-dumbbell-skullcrusher/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_overhead_tricep_extension = require('@bryllim/workout-guide/assets/dumbbell-overhead-tricep-extension/frame-1.png') as ImageSourcePropType;
const frame_single_arm_dumbbell_tricep_extension = require('@bryllim/workout-guide/assets/single-arm-dumbbell-tricep-extension/frame-1.png') as ImageSourcePropType;
const frame_bench_dip = require('@bryllim/workout-guide/assets/bench-dip/frame-1.png') as ImageSourcePropType;
const frame_tricep_kickback = require('@bryllim/workout-guide/assets/tricep-kickback/frame-1.png') as ImageSourcePropType;
const frame_wrist_extension = require('@bryllim/workout-guide/assets/wrist-extension/frame-1.png') as ImageSourcePropType;
const frame_farmer_carry = require('@bryllim/workout-guide/assets/farmer-carry/frame-1.png') as ImageSourcePropType;
const frame_crunch = require('@bryllim/workout-guide/assets/crunch/frame-1.png') as ImageSourcePropType;
const frame_reverse_crunch = require('@bryllim/workout-guide/assets/reverse-crunch/frame-1.png') as ImageSourcePropType;
const frame_russian_twist = require('@bryllim/workout-guide/assets/russian-twist/frame-1.png') as ImageSourcePropType;
const frame_bicycle_crunch = require('@bryllim/workout-guide/assets/bicycle-crunch/frame-1.png') as ImageSourcePropType;
const frame_mountain_climber = require('@bryllim/workout-guide/assets/mountain-climber/frame-1.png') as ImageSourcePropType;
const frame_dead_bug = require('@bryllim/workout-guide/assets/dead-bug/frame-1.png') as ImageSourcePropType;
const frame_bird_dog = require('@bryllim/workout-guide/assets/bird-dog/frame-1.png') as ImageSourcePropType;
const frame_pallof_press = require('@bryllim/workout-guide/assets/pallof-press/frame-1.png') as ImageSourcePropType;
const frame_cable_woodchop = require('@bryllim/workout-guide/assets/cable-woodchop/frame-1.png') as ImageSourcePropType;
const frame_half_kneeling_pallof_press = require('@bryllim/workout-guide/assets/half-kneeling-pallof-press/frame-1.png') as ImageSourcePropType;
const frame_cable_pallof_hold = require('@bryllim/workout-guide/assets/cable-pallof-hold/frame-1.png') as ImageSourcePropType;
const frame_hanging_knee_raise = require('@bryllim/workout-guide/assets/hanging-knee-raise/frame-1.png') as ImageSourcePropType;
const frame_captains_chair_knee_raise = require('@bryllim/workout-guide/assets/captains-chair-knee-raise/frame-1.png') as ImageSourcePropType;
const frame_decline_sit_up = require('@bryllim/workout-guide/assets/decline-sit-up/frame-1.png') as ImageSourcePropType;
const frame_weighted_crunch = require('@bryllim/workout-guide/assets/weighted-crunch/frame-1.png') as ImageSourcePropType;
const frame_weighted_russian_twist = require('@bryllim/workout-guide/assets/weighted-russian-twist/frame-1.png') as ImageSourcePropType;
const frame_dumbbell_side_bend = require('@bryllim/workout-guide/assets/dumbbell-side-bend/frame-1.png') as ImageSourcePropType;
const frame_elliptical = require('@bryllim/workout-guide/assets/elliptical/frame-1.png') as ImageSourcePropType;
const frame_swimming = require('@bryllim/workout-guide/assets/swimming/frame-1.png') as ImageSourcePropType;
const frame_jump_rope = require('@bryllim/workout-guide/assets/jump-rope/frame-1.png') as ImageSourcePropType;
const frame_assault_bike = require('@bryllim/workout-guide/assets/assault-bike/frame-1.png') as ImageSourcePropType;
const frame_skierg = require('@bryllim/workout-guide/assets/skierg/frame-1.png') as ImageSourcePropType;
const frame_hiking = require('@bryllim/workout-guide/assets/hiking/frame-1.png') as ImageSourcePropType;
const frame_treadmill_incline_walk = require('@bryllim/workout-guide/assets/treadmill-incline-walk/frame-1.png') as ImageSourcePropType;
const frame_battle_ropes = require('@bryllim/workout-guide/assets/battle-ropes/frame-1.png') as ImageSourcePropType;
const frame_incline_push_up = require('@bryllim/workout-guide/assets/incline-push-up/frame-1.png') as ImageSourcePropType;
const frame_knee_push_up = require('@bryllim/workout-guide/assets/knee-push-up/frame-1.png') as ImageSourcePropType;
const frame_wide_push_up = require('@bryllim/workout-guide/assets/wide-push-up/frame-1.png') as ImageSourcePropType;
const frame_diamond_push_up = require('@bryllim/workout-guide/assets/diamond-push-up/frame-1.png') as ImageSourcePropType;
const frame_decline_push_up = require('@bryllim/workout-guide/assets/decline-push-up/frame-1.png') as ImageSourcePropType;
const frame_pike_push_up = require('@bryllim/workout-guide/assets/pike-push-up/frame-1.png') as ImageSourcePropType;
const frame_feet_elevated_pike_push_up = require('@bryllim/workout-guide/assets/feet-elevated-pike-push-up/frame-1.png') as ImageSourcePropType;
const frame_archer_push_up = require('@bryllim/workout-guide/assets/archer-push-up/frame-1.png') as ImageSourcePropType;
const frame_typewriter_push_up = require('@bryllim/workout-guide/assets/typewriter-push-up/frame-1.png') as ImageSourcePropType;
const frame_explosive_push_up = require('@bryllim/workout-guide/assets/explosive-push-up/frame-1.png') as ImageSourcePropType;
const frame_hindu_push_up = require('@bryllim/workout-guide/assets/hindu-push-up/frame-1.png') as ImageSourcePropType;
const frame_scapular_push_up = require('@bryllim/workout-guide/assets/scapular-push-up/frame-1.png') as ImageSourcePropType;
const frame_push_up_shoulder_tap = require('@bryllim/workout-guide/assets/push-up-shoulder-tap/frame-1.png') as ImageSourcePropType;
const frame_wall_push_up = require('@bryllim/workout-guide/assets/wall-push-up/frame-1.png') as ImageSourcePropType;
const frame_wall_walk = require('@bryllim/workout-guide/assets/wall-walk/frame-1.png') as ImageSourcePropType;
const frame_wall_handstand_push_up = require('@bryllim/workout-guide/assets/wall-handstand-push-up/frame-1.png') as ImageSourcePropType;
const frame_handstand_push_up = require('@bryllim/workout-guide/assets/handstand-push-up/frame-1.png') as ImageSourcePropType;
const frame_chair_dip = require('@bryllim/workout-guide/assets/chair-dip/frame-1.png') as ImageSourcePropType;
const frame_doorway_row = require('@bryllim/workout-guide/assets/doorway-row/frame-1.png') as ImageSourcePropType;
const frame_towel_row = require('@bryllim/workout-guide/assets/towel-row/frame-1.png') as ImageSourcePropType;
const frame_prone_y_raise = require('@bryllim/workout-guide/assets/prone-y-raise/frame-1.png') as ImageSourcePropType;
const frame_prone_t_raise = require('@bryllim/workout-guide/assets/prone-t-raise/frame-1.png') as ImageSourcePropType;
const frame_superman = require('@bryllim/workout-guide/assets/superman/frame-1.png') as ImageSourcePropType;
const frame_superman_hold = require('@bryllim/workout-guide/assets/superman-hold/frame-1.png') as ImageSourcePropType;
const frame_reverse_snow_angel = require('@bryllim/workout-guide/assets/reverse-snow-angel/frame-1.png') as ImageSourcePropType;
const frame_dead_hang = require('@bryllim/workout-guide/assets/dead-hang/frame-1.png') as ImageSourcePropType;
const frame_active_hang = require('@bryllim/workout-guide/assets/active-hang/frame-1.png') as ImageSourcePropType;
const frame_scapular_pull_up = require('@bryllim/workout-guide/assets/scapular-pull-up/frame-1.png') as ImageSourcePropType;
const frame_negative_pull_up = require('@bryllim/workout-guide/assets/negative-pull-up/frame-1.png') as ImageSourcePropType;
const frame_commando_pull_up = require('@bryllim/workout-guide/assets/commando-pull-up/frame-1.png') as ImageSourcePropType;
const frame_l_sit_pull_up = require('@bryllim/workout-guide/assets/l-sit-pull-up/frame-1.png') as ImageSourcePropType;
const frame_towel_pull_up = require('@bryllim/workout-guide/assets/towel-pull-up/frame-1.png') as ImageSourcePropType;
const frame_bodyweight_squat = require('@bryllim/workout-guide/assets/bodyweight-squat/frame-1.png') as ImageSourcePropType;
const frame_pistol_squat = require('@bryllim/workout-guide/assets/pistol-squat/frame-1.png') as ImageSourcePropType;
const frame_assisted_pistol_squat = require('@bryllim/workout-guide/assets/assisted-pistol-squat/frame-1.png') as ImageSourcePropType;
const frame_shrimp_squat = require('@bryllim/workout-guide/assets/shrimp-squat/frame-1.png') as ImageSourcePropType;
const frame_cossack_squat = require('@bryllim/workout-guide/assets/cossack-squat/frame-1.png') as ImageSourcePropType;
const frame_sissy_squat = require('@bryllim/workout-guide/assets/sissy-squat/frame-1.png') as ImageSourcePropType;
const frame_forward_lunge = require('@bryllim/workout-guide/assets/forward-lunge/frame-1.png') as ImageSourcePropType;
const frame_lateral_lunge = require('@bryllim/workout-guide/assets/lateral-lunge/frame-1.png') as ImageSourcePropType;
const frame_curtsy_lunge = require('@bryllim/workout-guide/assets/curtsy-lunge/frame-1.png') as ImageSourcePropType;
const frame_skater_squat = require('@bryllim/workout-guide/assets/skater-squat/frame-1.png') as ImageSourcePropType;
const frame_single_leg_box_squat = require('@bryllim/workout-guide/assets/single-leg-box-squat/frame-1.png') as ImageSourcePropType;
const frame_step_down = require('@bryllim/workout-guide/assets/step-down/frame-1.png') as ImageSourcePropType;
const frame_calf_raise = require('@bryllim/workout-guide/assets/calf-raise/frame-1.png') as ImageSourcePropType;
const frame_single_leg_calf_raise = require('@bryllim/workout-guide/assets/single-leg-calf-raise/frame-1.png') as ImageSourcePropType;
const frame_glute_bridge_march = require('@bryllim/workout-guide/assets/glute-bridge-march/frame-1.png') as ImageSourcePropType;
const frame_frog_pump = require('@bryllim/workout-guide/assets/frog-pump/frame-1.png') as ImageSourcePropType;
const frame_donkey_kick = require('@bryllim/workout-guide/assets/donkey-kick/frame-1.png') as ImageSourcePropType;
const frame_fire_hydrant = require('@bryllim/workout-guide/assets/fire-hydrant/frame-1.png') as ImageSourcePropType;
const frame_clamshell = require('@bryllim/workout-guide/assets/clamshell/frame-1.png') as ImageSourcePropType;
const frame_hip_airplane = require('@bryllim/workout-guide/assets/hip-airplane/frame-1.png') as ImageSourcePropType;
const frame_side_lying_hip_abduction = require('@bryllim/workout-guide/assets/side-lying-hip-abduction/frame-1.png') as ImageSourcePropType;
const frame_side_lying_leg_raise = require('@bryllim/workout-guide/assets/side-lying-leg-raise/frame-1.png') as ImageSourcePropType;
const frame_lying_hamstring_walkout = require('@bryllim/workout-guide/assets/lying-hamstring-walkout/frame-1.png') as ImageSourcePropType;
const frame_towel_hamstring_curl = require('@bryllim/workout-guide/assets/towel-hamstring-curl/frame-1.png') as ImageSourcePropType;
const frame_stability_ball_hamstring_curl = require('@bryllim/workout-guide/assets/stability-ball-hamstring-curl/frame-1.png') as ImageSourcePropType;
const frame_banded_glute_bridge = require('@bryllim/workout-guide/assets/banded-glute-bridge/frame-1.png') as ImageSourcePropType;
const frame_banded_hip_thrust = require('@bryllim/workout-guide/assets/banded-hip-thrust/frame-1.png') as ImageSourcePropType;
const frame_banded_frog_pump = require('@bryllim/workout-guide/assets/banded-frog-pump/frame-1.png') as ImageSourcePropType;
const frame_banded_clamshell = require('@bryllim/workout-guide/assets/banded-clamshell/frame-1.png') as ImageSourcePropType;
const frame_banded_lateral_walk = require('@bryllim/workout-guide/assets/banded-lateral-walk/frame-1.png') as ImageSourcePropType;
const frame_banded_monster_walk = require('@bryllim/workout-guide/assets/banded-monster-walk/frame-1.png') as ImageSourcePropType;
const frame_banded_squat = require('@bryllim/workout-guide/assets/banded-squat/frame-1.png') as ImageSourcePropType;
const frame_banded_donkey_kick = require('@bryllim/workout-guide/assets/banded-donkey-kick/frame-1.png') as ImageSourcePropType;
const frame_banded_fire_hydrant = require('@bryllim/workout-guide/assets/banded-fire-hydrant/frame-1.png') as ImageSourcePropType;
const frame_banded_kickback = require('@bryllim/workout-guide/assets/banded-kickback/frame-1.png') as ImageSourcePropType;
const frame_banded_standing_hip_abduction = require('@bryllim/workout-guide/assets/banded-standing-hip-abduction/frame-1.png') as ImageSourcePropType;
const frame_banded_seated_hip_abduction = require('@bryllim/workout-guide/assets/banded-seated-hip-abduction/frame-1.png') as ImageSourcePropType;
const frame_band_pull_apart = require('@bryllim/workout-guide/assets/band-pull-apart/frame-1.png') as ImageSourcePropType;
const frame_banded_face_pull = require('@bryllim/workout-guide/assets/banded-face-pull/frame-1.png') as ImageSourcePropType;
const frame_banded_row = require('@bryllim/workout-guide/assets/banded-row/frame-1.png') as ImageSourcePropType;
const frame_banded_lat_pulldown = require('@bryllim/workout-guide/assets/banded-lat-pulldown/frame-1.png') as ImageSourcePropType;
const frame_banded_pallof_press = require('@bryllim/workout-guide/assets/banded-pallof-press/frame-1.png') as ImageSourcePropType;
const frame_banded_woodchop = require('@bryllim/workout-guide/assets/banded-woodchop/frame-1.png') as ImageSourcePropType;
const frame_banded_dead_bug = require('@bryllim/workout-guide/assets/banded-dead-bug/frame-1.png') as ImageSourcePropType;
const frame_hollow_body_hold = require('@bryllim/workout-guide/assets/hollow-body-hold/frame-1.png') as ImageSourcePropType;
const frame_hollow_rock = require('@bryllim/workout-guide/assets/hollow-rock/frame-1.png') as ImageSourcePropType;
const frame_v_up = require('@bryllim/workout-guide/assets/v-up/frame-1.png') as ImageSourcePropType;
const frame_flutter_kick = require('@bryllim/workout-guide/assets/flutter-kick/frame-1.png') as ImageSourcePropType;
const frame_lying_leg_raise = require('@bryllim/workout-guide/assets/lying-leg-raise/frame-1.png') as ImageSourcePropType;
const frame_toe_touch = require('@bryllim/workout-guide/assets/toe-touch/frame-1.png') as ImageSourcePropType;
const frame_heel_tap = require('@bryllim/workout-guide/assets/heel-tap/frame-1.png') as ImageSourcePropType;
const frame_plank_shoulder_tap = require('@bryllim/workout-guide/assets/plank-shoulder-tap/frame-1.png') as ImageSourcePropType;
const frame_plank_jack = require('@bryllim/workout-guide/assets/plank-jack/frame-1.png') as ImageSourcePropType;
const frame_bear_plank = require('@bryllim/workout-guide/assets/bear-plank/frame-1.png') as ImageSourcePropType;
const frame_bear_crawl = require('@bryllim/workout-guide/assets/bear-crawl/frame-1.png') as ImageSourcePropType;
const frame_crab_walk = require('@bryllim/workout-guide/assets/crab-walk/frame-1.png') as ImageSourcePropType;
const frame_inchworm = require('@bryllim/workout-guide/assets/inchworm/frame-1.png') as ImageSourcePropType;
const frame_l_sit_hold = require('@bryllim/workout-guide/assets/l-sit-hold/frame-1.png') as ImageSourcePropType;
const frame_seated_knee_tuck = require('@bryllim/workout-guide/assets/seated-knee-tuck/frame-1.png') as ImageSourcePropType;
const frame_side_plank_hip_dip = require('@bryllim/workout-guide/assets/side-plank-hip-dip/frame-1.png') as ImageSourcePropType;
const frame_copenhagen_plank = require('@bryllim/workout-guide/assets/copenhagen-plank/frame-1.png') as ImageSourcePropType;
const frame_dragon_flag = require('@bryllim/workout-guide/assets/dragon-flag/frame-1.png') as ImageSourcePropType;
const frame_burpee = require('@bryllim/workout-guide/assets/burpee/frame-1.png') as ImageSourcePropType;
const frame_half_burpee = require('@bryllim/workout-guide/assets/half-burpee/frame-1.png') as ImageSourcePropType;
const frame_squat_thrust = require('@bryllim/workout-guide/assets/squat-thrust/frame-1.png') as ImageSourcePropType;
const frame_high_knees = require('@bryllim/workout-guide/assets/high-knees/frame-1.png') as ImageSourcePropType;
const frame_jumping_jack = require('@bryllim/workout-guide/assets/jumping-jack/frame-1.png') as ImageSourcePropType;
const frame_skater_hop = require('@bryllim/workout-guide/assets/skater-hop/frame-1.png') as ImageSourcePropType;
const frame_lateral_shuffle = require('@bryllim/workout-guide/assets/lateral-shuffle/frame-1.png') as ImageSourcePropType;
const frame_fast_feet = require('@bryllim/workout-guide/assets/fast-feet/frame-1.png') as ImageSourcePropType;
const frame_sprawl = require('@bryllim/workout-guide/assets/sprawl/frame-1.png') as ImageSourcePropType;
const frame_seal_jack = require('@bryllim/workout-guide/assets/seal-jack/frame-1.png') as ImageSourcePropType;
const frame_cat_cow_stretch = require('@bryllim/workout-guide/assets/cat-cow-stretch/frame-1.png') as ImageSourcePropType;
const frame_arm_circles = require('@bryllim/workout-guide/assets/arm-circles/frame-1.png') as ImageSourcePropType;
const frame_worlds_greatest_stretch = require('@bryllim/workout-guide/assets/worlds-greatest-stretch/frame-1.png') as ImageSourcePropType;
const frame_leg_swings_stretch = require('@bryllim/workout-guide/assets/leg-swings-stretch/frame-1.png') as ImageSourcePropType;
const frame_torso_twist_stretch = require('@bryllim/workout-guide/assets/torso-twist-stretch/frame-1.png') as ImageSourcePropType;
const frame_doorway_chest_stretch = require('@bryllim/workout-guide/assets/doorway-chest-stretch/frame-1.png') as ImageSourcePropType;
const frame_childs_pose = require('@bryllim/workout-guide/assets/childs-pose/frame-1.png') as ImageSourcePropType;
const frame_kneeling_hip_flexor_stretch = require('@bryllim/workout-guide/assets/kneeling-hip-flexor-stretch/frame-1.png') as ImageSourcePropType;
const frame_hamstring_stretch = require('@bryllim/workout-guide/assets/hamstring-stretch/frame-1.png') as ImageSourcePropType;
const frame_standing_quad_stretch = require('@bryllim/workout-guide/assets/standing-quad-stretch/frame-1.png') as ImageSourcePropType;
const frame_seated_forward_fold_stretch = require('@bryllim/workout-guide/assets/seated-forward-fold-stretch/frame-1.png') as ImageSourcePropType;
const frame_cross_body_shoulder_stretch = require('@bryllim/workout-guide/assets/cross-body-shoulder-stretch/frame-1.png') as ImageSourcePropType;
const frame_wall_calf_stretch = require('@bryllim/workout-guide/assets/wall-calf-stretch/frame-1.png') as ImageSourcePropType;
const frame_butterfly_stretch = require('@bryllim/workout-guide/assets/butterfly-stretch/frame-1.png') as ImageSourcePropType;

export const EXERCISE_FRAMES: Record<string, ImageSourcePropType> = {
  'bench-press': frame_bench_press,
  'incline-bench-press': frame_incline_bench_press,
  'incline-dumbbell-press': frame_incline_dumbbell_press,
  'dumbbell-bench-press': frame_dumbbell_bench_press,
  'decline-bench-press': frame_decline_bench_press,
  'machine-chest-press': frame_machine_chest_press,
  'pec-deck': frame_pec_deck,
  'cable-fly': frame_cable_fly,
  'push-up': frame_push_up,
  'weighted-push-up': frame_weighted_push_up,
  'overhead-press': frame_overhead_press,
  'seated-dumbbell-press': frame_seated_dumbbell_press,
  'arnold-press': frame_arnold_press,
  'lateral-raise': frame_lateral_raise,
  'cable-lateral-raise': frame_cable_lateral_raise,
  'front-raise': frame_front_raise,
  'rear-delt-fly': frame_rear_delt_fly,
  'reverse-pec-deck': frame_reverse_pec_deck,
  'face-pull': frame_face_pull,
  'upright-row': frame_upright_row,
  'deadlift': frame_deadlift,
  'romanian-deadlift': frame_romanian_deadlift,
  'barbell-row': frame_barbell_row,
  't-bar-row': frame_t_bar_row,
  'dumbbell-bent-over-row': frame_dumbbell_bent_over_row,
  'one-arm-dumbbell-row': frame_one_arm_dumbbell_row,
  'chest-supported-row': frame_chest_supported_row,
  'seated-row': frame_seated_row,
  'machine-row': frame_machine_row,
  'lat-pulldown': frame_lat_pulldown,
  'close-grip-lat-pulldown': frame_close_grip_lat_pulldown,
  'straight-arm-pulldown': frame_straight_arm_pulldown,
  'pull-up': frame_pull_up,
  'assisted-pull-up': frame_assisted_pull_up,
  'weighted-pull-up': frame_weighted_pull_up,
  'chin-up': frame_chin_up,
  'shrug': frame_shrug,
  'squat': frame_squat,
  'front-squat': frame_front_squat,
  'hack-squat': frame_hack_squat,
  'leg-press': frame_leg_press,
  'bulgarian-split-squat': frame_bulgarian_split_squat,
  'walking-lunge': frame_walking_lunge,
  'step-up': frame_step_up,
  'leg-extension': frame_leg_extension,
  'leg-curl': frame_leg_curl,
  'seated-leg-curl': frame_seated_leg_curl,
  'hip-thrust': frame_hip_thrust,
  'glute-bridge': frame_glute_bridge,
  'good-morning': frame_good_morning,
  'standing-calf-raise': frame_standing_calf_raise,
  'seated-calf-raise': frame_seated_calf_raise,
  'bicep-curl': frame_bicep_curl,
  'hammer-curl': frame_hammer_curl,
  'preacher-curl': frame_preacher_curl,
  'cable-curl': frame_cable_curl,
  'reverse-curl': frame_reverse_curl,
  'wrist-curl': frame_wrist_curl,
  'tricep-pushdown': frame_tricep_pushdown,
  'overhead-tricep-extension': frame_overhead_tricep_extension,
  'skull-crusher': frame_skull_crusher,
  'close-grip-bench-press': frame_close_grip_bench_press,
  'dip': frame_dip,
  'assisted-dip': frame_assisted_dip,
  'plank': frame_plank,
  'side-plank': frame_side_plank,
  'hanging-leg-raise': frame_hanging_leg_raise,
  'cable-crunch': frame_cable_crunch,
  'ab-wheel': frame_ab_wheel,
  'running': frame_running,
  'walking': frame_walking,
  'cycling': frame_cycling,
  'rowing': frame_rowing,
  'stair-climber': frame_stair_climber,
  'dumbbell-fly': frame_dumbbell_fly,
  'incline-cable-fly': frame_incline_cable_fly,
  'decline-dumbbell-press': frame_decline_dumbbell_press,
  'smith-machine-bench-press': frame_smith_machine_bench_press,
  'landmine-press': frame_landmine_press,
  'chest-dip': frame_chest_dip,
  'weighted-dip': frame_weighted_dip,
  'machine-shoulder-press': frame_machine_shoulder_press,
  'standing-dumbbell-press': frame_standing_dumbbell_press,
  'push-press': frame_push_press,
  'machine-lateral-raise': frame_machine_lateral_raise,
  'cable-front-raise': frame_cable_front_raise,
  'plate-front-raise': frame_plate_front_raise,
  'bent-over-rear-delt-raise': frame_bent_over_rear_delt_raise,
  'cable-rear-delt-fly': frame_cable_rear_delt_fly,
  'pendlay-row': frame_pendlay_row,
  'inverted-row': frame_inverted_row,
  'meadows-row': frame_meadows_row,
  'single-arm-cable-row': frame_single_arm_cable_row,
  'wide-grip-lat-pulldown': frame_wide_grip_lat_pulldown,
  'neutral-grip-pull-up': frame_neutral_grip_pull_up,
  'assisted-chin-up': frame_assisted_chin_up,
  'weighted-chin-up': frame_weighted_chin_up,
  'rack-pull': frame_rack_pull,
  'back-extension': frame_back_extension,
  'dumbbell-shrug': frame_dumbbell_shrug,
  'goblet-squat': frame_goblet_squat,
  'smith-machine-squat': frame_smith_machine_squat,
  'belt-squat': frame_belt_squat,
  'sumo-deadlift': frame_sumo_deadlift,
  'trap-bar-deadlift': frame_trap_bar_deadlift,
  'lying-leg-curl': frame_lying_leg_curl,
  'nordic-hamstring-curl': frame_nordic_hamstring_curl,
  'single-leg-romanian-deadlift': frame_single_leg_romanian_deadlift,
  'reverse-lunge': frame_reverse_lunge,
  'split-squat': frame_split_squat,
  'cable-kickback': frame_cable_kickback,
  'hip-abduction-machine': frame_hip_abduction_machine,
  'single-leg-glute-bridge': frame_single_leg_glute_bridge,
  'barbell-glute-bridge': frame_barbell_glute_bridge,
  'dumbbell-glute-bridge': frame_dumbbell_glute_bridge,
  'dumbbell-hip-thrust': frame_dumbbell_hip_thrust,
  'smith-machine-hip-thrust': frame_smith_machine_hip_thrust,
  'smith-machine-romanian-deadlift': frame_smith_machine_romanian_deadlift,
  'dumbbell-romanian-deadlift': frame_dumbbell_romanian_deadlift,
  'kettlebell-romanian-deadlift': frame_kettlebell_romanian_deadlift,
  'cable-pull-through': frame_cable_pull_through,
  'machine-glute-kickback': frame_machine_glute_kickback,
  'cable-standing-hip-abduction': frame_cable_standing_hip_abduction,
  'cable-standing-hip-adduction': frame_cable_standing_hip_adduction,
  'hip-adduction-machine': frame_hip_adduction_machine,
  'smith-machine-bulgarian-split-squat': frame_smith_machine_bulgarian_split_squat,
  'smith-machine-reverse-lunge': frame_smith_machine_reverse_lunge,
  'smith-machine-split-squat': frame_smith_machine_split_squat,
  'heel-elevated-goblet-squat': frame_heel_elevated_goblet_squat,
  'dumbbell-sumo-squat': frame_dumbbell_sumo_squat,
  'dumbbell-sumo-deadlift': frame_dumbbell_sumo_deadlift,
  'front-foot-elevated-split-squat': frame_front_foot_elevated_split_squat,
  'deficit-reverse-lunge': frame_deficit_reverse_lunge,
  'dumbbell-lateral-lunge': frame_dumbbell_lateral_lunge,
  'dumbbell-curtsy-lunge': frame_dumbbell_curtsy_lunge,
  'landmine-squat': frame_landmine_squat,
  'landmine-romanian-deadlift': frame_landmine_romanian_deadlift,
  'kettlebell-swing': frame_kettlebell_swing,
  'glute-focused-back-extension': frame_glute_focused_back_extension,
  'reverse-hyperextension': frame_reverse_hyperextension,
  'donkey-calf-raise': frame_donkey_calf_raise,
  'leg-press-calf-raise': frame_leg_press_calf_raise,
  'wall-sit': frame_wall_sit,
  'jump-squat': frame_jump_squat,
  'incline-dumbbell-curl': frame_incline_dumbbell_curl,
  'concentration-curl': frame_concentration_curl,
  'ez-bar-curl': frame_ez_bar_curl,
  'spider-curl': frame_spider_curl,
  'rope-hammer-curl': frame_rope_hammer_curl,
  'drag-curl': frame_drag_curl,
  'rope-tricep-pushdown': frame_rope_tricep_pushdown,
  'dumbbell-skull-crusher': frame_dumbbell_skull_crusher,
  'single-dumbbell-skullcrusher': frame_single_dumbbell_skullcrusher,
  'dumbbell-overhead-tricep-extension': frame_dumbbell_overhead_tricep_extension,
  'single-arm-dumbbell-tricep-extension': frame_single_arm_dumbbell_tricep_extension,
  'bench-dip': frame_bench_dip,
  'tricep-kickback': frame_tricep_kickback,
  'wrist-extension': frame_wrist_extension,
  'farmer-carry': frame_farmer_carry,
  'crunch': frame_crunch,
  'reverse-crunch': frame_reverse_crunch,
  'russian-twist': frame_russian_twist,
  'bicycle-crunch': frame_bicycle_crunch,
  'mountain-climber': frame_mountain_climber,
  'dead-bug': frame_dead_bug,
  'bird-dog': frame_bird_dog,
  'pallof-press': frame_pallof_press,
  'cable-woodchop': frame_cable_woodchop,
  'half-kneeling-pallof-press': frame_half_kneeling_pallof_press,
  'cable-pallof-hold': frame_cable_pallof_hold,
  'hanging-knee-raise': frame_hanging_knee_raise,
  'captains-chair-knee-raise': frame_captains_chair_knee_raise,
  'decline-sit-up': frame_decline_sit_up,
  'weighted-crunch': frame_weighted_crunch,
  'weighted-russian-twist': frame_weighted_russian_twist,
  'dumbbell-side-bend': frame_dumbbell_side_bend,
  'elliptical': frame_elliptical,
  'swimming': frame_swimming,
  'jump-rope': frame_jump_rope,
  'assault-bike': frame_assault_bike,
  'skierg': frame_skierg,
  'hiking': frame_hiking,
  'treadmill-incline-walk': frame_treadmill_incline_walk,
  'battle-ropes': frame_battle_ropes,
  'incline-push-up': frame_incline_push_up,
  'knee-push-up': frame_knee_push_up,
  'wide-push-up': frame_wide_push_up,
  'diamond-push-up': frame_diamond_push_up,
  'decline-push-up': frame_decline_push_up,
  'pike-push-up': frame_pike_push_up,
  'feet-elevated-pike-push-up': frame_feet_elevated_pike_push_up,
  'archer-push-up': frame_archer_push_up,
  'typewriter-push-up': frame_typewriter_push_up,
  'explosive-push-up': frame_explosive_push_up,
  'hindu-push-up': frame_hindu_push_up,
  'scapular-push-up': frame_scapular_push_up,
  'push-up-shoulder-tap': frame_push_up_shoulder_tap,
  'wall-push-up': frame_wall_push_up,
  'wall-walk': frame_wall_walk,
  'wall-handstand-push-up': frame_wall_handstand_push_up,
  'handstand-push-up': frame_handstand_push_up,
  'chair-dip': frame_chair_dip,
  'doorway-row': frame_doorway_row,
  'towel-row': frame_towel_row,
  'prone-y-raise': frame_prone_y_raise,
  'prone-t-raise': frame_prone_t_raise,
  'superman': frame_superman,
  'superman-hold': frame_superman_hold,
  'reverse-snow-angel': frame_reverse_snow_angel,
  'dead-hang': frame_dead_hang,
  'active-hang': frame_active_hang,
  'scapular-pull-up': frame_scapular_pull_up,
  'negative-pull-up': frame_negative_pull_up,
  'commando-pull-up': frame_commando_pull_up,
  'l-sit-pull-up': frame_l_sit_pull_up,
  'towel-pull-up': frame_towel_pull_up,
  'bodyweight-squat': frame_bodyweight_squat,
  'pistol-squat': frame_pistol_squat,
  'assisted-pistol-squat': frame_assisted_pistol_squat,
  'shrimp-squat': frame_shrimp_squat,
  'cossack-squat': frame_cossack_squat,
  'sissy-squat': frame_sissy_squat,
  'forward-lunge': frame_forward_lunge,
  'lateral-lunge': frame_lateral_lunge,
  'curtsy-lunge': frame_curtsy_lunge,
  'skater-squat': frame_skater_squat,
  'single-leg-box-squat': frame_single_leg_box_squat,
  'step-down': frame_step_down,
  'calf-raise': frame_calf_raise,
  'single-leg-calf-raise': frame_single_leg_calf_raise,
  'glute-bridge-march': frame_glute_bridge_march,
  'frog-pump': frame_frog_pump,
  'donkey-kick': frame_donkey_kick,
  'fire-hydrant': frame_fire_hydrant,
  'clamshell': frame_clamshell,
  'hip-airplane': frame_hip_airplane,
  'side-lying-hip-abduction': frame_side_lying_hip_abduction,
  'side-lying-leg-raise': frame_side_lying_leg_raise,
  'lying-hamstring-walkout': frame_lying_hamstring_walkout,
  'towel-hamstring-curl': frame_towel_hamstring_curl,
  'stability-ball-hamstring-curl': frame_stability_ball_hamstring_curl,
  'banded-glute-bridge': frame_banded_glute_bridge,
  'banded-hip-thrust': frame_banded_hip_thrust,
  'banded-frog-pump': frame_banded_frog_pump,
  'banded-clamshell': frame_banded_clamshell,
  'banded-lateral-walk': frame_banded_lateral_walk,
  'banded-monster-walk': frame_banded_monster_walk,
  'banded-squat': frame_banded_squat,
  'banded-donkey-kick': frame_banded_donkey_kick,
  'banded-fire-hydrant': frame_banded_fire_hydrant,
  'banded-kickback': frame_banded_kickback,
  'banded-standing-hip-abduction': frame_banded_standing_hip_abduction,
  'banded-seated-hip-abduction': frame_banded_seated_hip_abduction,
  'band-pull-apart': frame_band_pull_apart,
  'banded-face-pull': frame_banded_face_pull,
  'banded-row': frame_banded_row,
  'banded-lat-pulldown': frame_banded_lat_pulldown,
  'banded-pallof-press': frame_banded_pallof_press,
  'banded-woodchop': frame_banded_woodchop,
  'banded-dead-bug': frame_banded_dead_bug,
  'hollow-body-hold': frame_hollow_body_hold,
  'hollow-rock': frame_hollow_rock,
  'v-up': frame_v_up,
  'flutter-kick': frame_flutter_kick,
  'lying-leg-raise': frame_lying_leg_raise,
  'toe-touch': frame_toe_touch,
  'heel-tap': frame_heel_tap,
  'plank-shoulder-tap': frame_plank_shoulder_tap,
  'plank-jack': frame_plank_jack,
  'bear-plank': frame_bear_plank,
  'bear-crawl': frame_bear_crawl,
  'crab-walk': frame_crab_walk,
  'inchworm': frame_inchworm,
  'l-sit-hold': frame_l_sit_hold,
  'seated-knee-tuck': frame_seated_knee_tuck,
  'side-plank-hip-dip': frame_side_plank_hip_dip,
  'copenhagen-plank': frame_copenhagen_plank,
  'dragon-flag': frame_dragon_flag,
  'burpee': frame_burpee,
  'half-burpee': frame_half_burpee,
  'squat-thrust': frame_squat_thrust,
  'high-knees': frame_high_knees,
  'jumping-jack': frame_jumping_jack,
  'skater-hop': frame_skater_hop,
  'lateral-shuffle': frame_lateral_shuffle,
  'fast-feet': frame_fast_feet,
  'sprawl': frame_sprawl,
  'seal-jack': frame_seal_jack,
  'cat-cow-stretch': frame_cat_cow_stretch,
  'arm-circles': frame_arm_circles,
  'worlds-greatest-stretch': frame_worlds_greatest_stretch,
  'leg-swings-stretch': frame_leg_swings_stretch,
  'torso-twist-stretch': frame_torso_twist_stretch,
  'doorway-chest-stretch': frame_doorway_chest_stretch,
  'childs-pose': frame_childs_pose,
  'kneeling-hip-flexor-stretch': frame_kneeling_hip_flexor_stretch,
  'hamstring-stretch': frame_hamstring_stretch,
  'standing-quad-stretch': frame_standing_quad_stretch,
  'seated-forward-fold-stretch': frame_seated_forward_fold_stretch,
  'cross-body-shoulder-stretch': frame_cross_body_shoulder_stretch,
  'wall-calf-stretch': frame_wall_calf_stretch,
  'butterfly-stretch': frame_butterfly_stretch,
};
